### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by farismhmd1** [ameriod/Android-Pdf-Viewer#1]
On my android oreo phone app crash after the swipe of 3rd pdf.

03-11 11:55:31.989 8600-8605/me.ameriod.pdfviewer I/zygote64: Increasing code cache capacity to 256KB
03-11 11:55:32.163 8600-8600/me.ameriod.pdfviewer D/AndroidRuntime: Shutting down VM
03-11 11:55:32.174 8600-8600/me.ameriod.pdfviewer E/AndroidRuntime: FATAL EXCEPTION: main
                                                                    Process: me.ameriod.pdfviewer, PID: 8600
                                                                    java.lang.IllegalStateException: Already closed
                                                                        at android.graphics.pdf.PdfRenderer$Page.throwIfClosed(PdfRenderer.java:467)
                                                                        at android.graphics.pdf.PdfRenderer$Page.close(PdfRenderer.java:440)
                                                                        at me.ameriod.lib.pdfviewer.PdfViewerView$PdfAdapter.instantiateItem(PdfViewerView.java:155)
                                                                        at android.support.v4.view.ViewPager.addNewItem(ViewPager.java:1002)
                                                                        at android.support.v4.view.ViewPager.populate(ViewPager.java:1216)
                                                                        at android.support.v4.view.ViewPager.populate(ViewPager.java:1084)
                                                                        at android.support.v4.view.ViewPager$3.run(ViewPager.java:267)
                                                                        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966)
                                                                        at android.view.Choreographer.doCallbacks(Choreographer.java:778)
                                                                        at android.view.Choreographer.doFrame(Choreographer.java:710)
                                                                        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
                                                                        at android.os.Handler.handleCallback(Handler.java:789)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                        at android.os.Looper.loop(Looper.java:164)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6809)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
03-11 11:55:32.184 8600-8600/me.ameriod.pdfviewer D/AppTracker: App Event: crash

**Comment by rahulkhatri19** [comment]
Use try catch block . In PdfViewerView.java file in lib. Example :  @Override
        public Object instantiateItem(ViewGroup container, int position) {
            if (currentPage != null) {
try {
    currentPage.close();
} catch (Exception e){
    e.printStackTrace();
}
            }

and at 

 @Override
        public void destroyItem(ViewGroup container, int position, Object object) {
            try {
                if (currentPage != null) {
                   try{
                       currentPage.close();
                   } catch (Exception e){
                       e.printStackTrace();
                   }
                }
            } catch (Exception e) {
                e.printStackTrace();
                // no op, need to make sure it is closed
            }

            container.removeView((View) object);
        }

**Comment by Programmingtimes** [comment]
this app is totally buggy it does not have any code ethic. sorry author. the sample file does not have any id finder or initiation!
